-- Last updated: 09/07/2026, 15:07:22
WITH ALL_IDS AS (
    SELECT REQUESTER_ID AS ID
    FROM REQUESTACCEPTED

    UNION ALL

    SELECT ACCEPTER_ID AS ID
    FROM REQUESTACCEPTED
)

SELECT
    ID,
    COUNT(ID) AS NUM
FROM ALL_IDS
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;